// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCewvr-ogK-zMNPLpEj8pCekCIYQxlxiU',
    appId: '1:202784332047:web:4b655ea5b74e8aa99a867a',
    messagingSenderId: '202784332047',
    projectId: 'campus-assistant-3f1a7',
    authDomain: 'campus-assistant-3f1a7.firebaseapp.com',
    storageBucket: 'campus-assistant-3f1a7.firebasestorage.app',
    measurementId: 'G-ECNLLR8ZEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE_invrkxzdmE-RYOdZjzhWq-SW00FBUw',
    appId: '1:202784332047:android:c578ea23225b75c09a867a',
    messagingSenderId: '202784332047',
    projectId: 'campus-assistant-3f1a7',
    storageBucket: 'campus-assistant-3f1a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCVBoyFeyyeaWeptA5rbjh4UGkRXU0WPA',
    appId: '1:202784332047:ios:df0238333593fe749a867a',
    messagingSenderId: '202784332047',
    projectId: 'campus-assistant-3f1a7',
    storageBucket: 'campus-assistant-3f1a7.firebasestorage.app',
    iosBundleId: 'com.example.campusAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCVBoyFeyyeaWeptA5rbjh4UGkRXU0WPA',
    appId: '1:202784332047:ios:df0238333593fe749a867a',
    messagingSenderId: '202784332047',
    projectId: 'campus-assistant-3f1a7',
    storageBucket: 'campus-assistant-3f1a7.firebasestorage.app',
    iosBundleId: 'com.example.campusAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCewvr-ogK-zMNPLpEj8pCekCIYQxlxiU',
    appId: '1:202784332047:web:91904e6646c5441c9a867a',
    messagingSenderId: '202784332047',
    projectId: 'campus-assistant-3f1a7',
    authDomain: 'campus-assistant-3f1a7.firebaseapp.com',
    storageBucket: 'campus-assistant-3f1a7.firebasestorage.app',
    measurementId: 'G-XKB761KXE9',
  );
}
